### ISSUE TITLE
Expose "_total" after creating the scroll

### ISSUE THREAD

**Issue by rubennorte** [alcacoop/elasticsearch-scroll-stream#11]
When receiving the response from the scroll creation request, the number of matching documents is received. Could you expose it in "stream._total" right when it's available?

**Comment by francov** [comment]
Hi, actually the scroll creation (the first query) and subsequent calls with the scroll_id are encapsulated into the `Readable#_read` method implementation. So actually the 'right when it's available' translates to 'the first `data` event on the stream'.
To obtain the total already on stream creation I need to move the first query to elastic into the constructor of the Stream. And this implies consistent changes to the api: in fact I would have to add a callback parameter to the constructor with a `total` parameter available to you when the first query completes...

The faster I can do now is to set the `_total` property available not only when the stream interrupts (now is this way that works), but from the beginning of stream consumption (on the first `data` event available)

**Comment by rubennorte** [comment]
> The faster I can do now is to set the _total property available not only when the stream interrupts (now is this way that works), but from the beginning of stream consumption (on the first data event available)

That's exactly what I was talking about ;)

I see that you just committed it on master. Thanks!

**Comment by shahidmau** [comment]
I am not getting _total value, kindly paste sample code.
