### ISSUE TITLE
Clear Scroll API doesn't work for Elasticsearch 5.1.1

### ISSUE THREAD

**Issue by sriharshakappala** [alcacoop/elasticsearch-scroll-stream#15]
The clear scroll API call fails if the elasticsearch version is 5.1.1

This happens because we send scroll id as array in 5.1

```
DELETE /_search/scroll
{
    "scroll_id" : ["DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ=="]
}
```

whereas for newer versions we send it as string

```
DELETE /_search/scroll
{
    "scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ=="
}
```

**Comment by francov** [comment]
I'm sorry, but this issue is not related to this library.
Moreover I think you are confusing the REST apis with the javascript apis.

Anyway if you want to "force close early" the stream you can call the `close()` method (see README, and test code examples):

```javascript
es_stream.on('data', function(data) {
  ...
  es_stream.close();
});
```

**Comment by sriharshakappala** [comment]
@francov 

Changing this

```js
self._client.clearScroll({ scrollId: response._scroll_id }, function(err, res) {});
```

to the below worked for ES version 5.1.1

```js
self._client.clearScroll({ scrollId: [response._scroll_id] }, function(err, res) {});
```

Probably we can try to make it support for all the versions. That's what I meant

**Comment by francov** [comment]
Can you please specify which version of elasticsearch.js are you using in package.json?
Thank you

**Comment by francov** [comment]
Ok, I just verified the problem with Elasticsearch 5.3.0.
I didn't notice the problem, because I was using Elasticsearch 6.5.1 in the tests, which is not affected.

As soon as possible I will release a new hot-fix by providing your solution, and updating all the package dependencies. 
In the meantime, you are welcome to make me a pull request :) 

Let me know,
Thanks

**Comment by sriharshakappala** [comment]
@francov Sure, I will make the fix and raise a PR! :)
