### ISSUE TITLE
Compatibility with the new elastic search js client ?

### ISSUE THREAD

**Issue by gmeurant** [alcacoop/elasticsearch-scroll-stream#17]
Hello,

It would be great to make this library compatible with the new official js client: @elastic/elasticsearch (https://www.elastic.co/fr/blog/new-elasticsearch-javascript-client-released)

For what I have tested, the client seems to wrap the response in a new "body" object, so this library fails on the line 55 of elasticsearch-stream.js:
`self._total = (typeof response.hits.total === 'object') ? response.hits.total.value : response.hits.total;`
because response.hits is undefined.
If we use response.body instead of the response object, it seems to work.

Best regards

**Comment by francov** [comment]
Thank you for your report!
I was already considering adding support to the new official js client. I'll publish soon the upgrade.
Stay tuned! :)

**Comment by francov** [comment]
Just released the update!

**Comment by gmeurant** [comment]
Nice! I'll give it a try as soon as possible, thanks.

**Comment by mchelen** [comment]
Shouldn't this be in `dependencies` and not `devDependencies` since it's a runtime requirement?

**Comment by francov** [comment]
Elasticsearch is not a direct dependency of this library, which was also created with the intent to support different nodejs clients, in fact the esclient object is passed as a parameter.
The `elasticsearch` package is located in `devDependencies` only for running the test suite.
