### ISSUE TITLE
how to get all fields? and '_id' field?

### ISSUE THREAD

**Issue by teebu** [alcacoop/elasticsearch-scroll-stream#3]
I'm trying to get the value of '_id', its not returning anything. Also, I'm trying to get all fields, that is also not working. I tried commenting out fields, that gave me nothing.

The culprit is this: ```self.push(JSON.stringify(hit.fields));``` its giving back fields, not the whole doc.

as a dirty quick fix. i added hit.fields['_id'] = hit['_id']

**Comment by francov** [comment]
Hi,
I think you should update the packege to the latest version (1.0.4), in which this kind of issue was already addressed, see here https://github.com/alcacoop/elasticsearch-scroll-stream/blob/master/lib/elasticsearch-stream.js#L45.

Let me know if this solves the _id throuble too.

**Comment by francov** [comment]
I just opened a new issue for the `_id` question #4 . I'll fix as soon as possible. Thank you!
