### ISSUE TITLE
How to abort properly ?

### ISSUE THREAD

**Issue by Marsup** [alcacoop/elasticsearch-scroll-stream#8]
Hello,

I have a complex use case that can't rely solely on elasticsearch, and so I need to interrupt the stream when I get the answer I need, would you have an idea about how to properly stop the stream from reading from ES ? Should I just call `close()` on it ?

The scroll will only live for the time I specified so I guess it's ok, but I wanted to know if it would cause any problem or leak for this library in your opinion.

Thanks.

**Comment by francov** [comment]
Hi,
I think you can't stop the source at the moment. The `close()` method exists only for an `fs.ReadStream` not for a generic `ReadableStream`. The official documentation on Stream APIs has never been complete or clear on the possible ways to stop a stream from reading the source.
So I think that a possible way to address this situation (of which, sincerely, I have never had the need) is to implement an `es_stream.stopScroll()` method that will stop the scroll recursion internally.
What do you think about this? I can code that method as soon as possible...

**Comment by Marsup** [comment]
Maybe sticking to terms that are more common in the node streams world like `close` or `destroy` would be better for discoverability ? But on the principle sure, that would work for me.

**Comment by francov** [comment]
Added `close() method` in [v1.1.0](https://github.com/alcacoop/elasticsearch-scroll-stream/tree/v1.1.0)

**Comment by Marsup** [comment]
Thanks a lot, tested it just now, works perfectly, I just need to ignore the remaining documents that has already been buffered in the stream.
